name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[dev]
      - name: Lint
        run: |
          black --check src tests
          isort --check-only src tests
          flake8 src tests
          mypy src
      - name: Test
        run: pytest
